### ISSUE TITLE
PrefixSuffixUtil and MonthlyExpense.getStatus() not found

### ISSUE THREAD

**Issue by atv-axiomatic** [TatuLund/devday-demo-flow#1]
Quite a few errors found in GridView.java with PrefixSuffixUtil and .getStatus() not found.

Specifically, while running 'mvn jetty:run' I receive 7 errors relating to these two issues where "Java: cannot find symbol".

Perhaps you've accidentally removed the PrefixSuffixUtil class as well as the .getStatus() method in your MonthlyExpense object?

![devday-demo-error](https://user-images.githubusercontent.com/60635737/104540657-e5721080-55ed-11eb-84a2-0aa581ae750d.png)

**Comment by TatuLund** [comment]
Thanks for your feedback, I had forgotten those in my last commit, added them now.

I added the prefix thing also to our cook book as well:

https://cookbook.vaadin.com/prefix-util
